<form action="" method="post" id="auth-form" novalidate="novalidate">
<div id="form-content">
        <fieldset>
            <h3>Ingrese su clave y contraseña</h3>
            <div class="fieldgroup">
                <label for="username">Usuario</label>
                <input type="text" id="username" name="username">
            </div>

            <div class="fieldgroup">
                <label for="password">Clave</label>
                <input type="password" id="password" name="password">
            </div>

            <div class="fieldgroup">
                <input type="submit" value="Ingresar" class="submit">
            </div>

        </fieldset>
    </div>
</form>
