<?php
$this->HeadScript()->appendScript("
		$().ready(function() {
			CKEDITOR.replace( 'contenido', {
    			filebrowserBrowseUrl : '/admin/index/elfinder', // eg. 'includes/elFinder/elfinder.html'
  			});
		});"
);
/*  */
?>
<h1>Edición de noticia</h1>
<br>
<form action="" method=post>
	<table>
		<tr>
			<th>Título</th><td><input type="text" name="titulo" size="100" value="<?php echo $noticia->title;?>"/></td>			
		</tr>
		<tr>
			<th>Contenido</th><td><textarea name="contenido" rows="50" cols="120" class="ckeditor"><?php echo $noticia->content;?></textarea></td>
		</tr>
		<tr>
			<th>URL</th><td><input type="text" name="url" size="100" value="<?php echo $noticia->url;?>"/></td>			
		</tr>	
		<tr>
			<td colspan="2"><div style="float:right;"><input type="submit" value="Guardar"/></div></td>			
		</tr>		
	</table>
</form>