<div class="post"> 

<p>
    <a href="<?php echo $this->url('admin', array('controller'=>'noticia','action'=>'add'));?>">Crear nueva noticia</a>
</p>
<br/>
	<table class="tcontent"><tr><th>Título</th><th>Autor</th><th>Creacion</th><th>Modificado</th><th>&nbsp;</th><th>&nbsp;</th><tr>
			<?php foreach ($noticias as $noticia) : ?>
				<tr>
					<td><a href="<?php echo "/".$this->escapeHtml($noticia->url);?>"><?php echo $this->escapeHtml($noticia->title);?></a></td>
					<td><?php echo $this->escapeHtml($noticia->user_id);?></td>
					<td><?php echo $this->escapeHtml($noticia->created);?></td>
					<td><?php echo $this->escapeHtml($noticia->modified);?></td>
   				    <td><a href="<?php echo $this->url('admin', array('controller'=>'noticia','action'=>'edit','id'=>$noticia->id));?>">Editar</a></td>
 					<td><a href="<?php echo $this->url('admin', array('controller'=>'noticia','action'=>'delete','id'=>$noticia->id));?>">Borrar</a></td>
				</tr>	 
		<?php endforeach; ?>
	</table>	
</div>
